### PR TITLE
Add CN mode for users in Chinese mainland

### PR DESCRIPTION
**Pull request by GeorgeDong32**
## What's difference
I replace the `Bing.URL` with the `CompatibleURL` to make the program run better in Chinese mainland. A new AppOption is also introduced to choose whether to turn on the CN mode(default is closed). 

## Test Result
I ran the new program 6 times and so far nothing has been out of the ordinary. The operating environment and modes are as follows:

|    |  Information  | 
| :------------------ | :----: |
|  OS  |  Windows11 Beta  | 
|  IDE  |  Visual Studio  | 
|  Solution Configuration  |  Debug-Any CPU  |
|  mode  |  -nh -cn & -nh  |
|  location  | Chinese mainland |

## Other information
However, the naming of variables and the style of the code may not be quite the same as what you are currently using. If you want to add this feature, you can use it as a reference.

### CODE REVIEW

**Comment by Tom60chat** [comment]
Hello, thank you for your PR.

I didn't know there was a Chinese version of bing.

Personally, I wouldn't implement this feature like this, so it requires more thought.
But it's a good solution for now.

I probably won't accept this pr, probably, I'll leave it open until I decide.

**Comment by GeorgeDong32** [comment]
Thanks for Review! Indeed, this is only a temporary solution. However, considering that Chinese mainland users may be relatively small, the time you pay for this feature may not be cost-effective 😂. As a beginner, I'm excited to learn something from this project, whether you end up agreeing with this PR or not.

**Comment by GeorgeDong32** [comment]
Hi, after testing for some time, I found that the previous problem was caused by a problem with Bing's redirect server in China. When this server resumes normal operation, the original code can also complete the operation normally. You may consider closing this PR. 😂

**Comment by Tom60chat** [comment]
Glade, this issue has been fixed by itself, nevertheless a way to set manually bing country would not be a bad idea.

**Pull request closed without merging**
