### PR TITLE
discord webhook logger

### PR DESCRIPTION
**Pull request by haq**
**do not merge as this pr is still wip**

- refactored how loggers are implemented
- added discord webhook logger

furthermore, thoughts on moving arguments into Settings.json?

### CODE REVIEW

**Comment by Tom60chat** [comment]
Yep, that was an idea to be abble to put arguments in Settings.json, but still let argument.

I belive you can fork MRF, and after you done do a pr.

**Comment by haq** [comment]
this pr is done, but I don't recommend anyone use discord logger as it will spam your channel.

a future pr should re-write what is logged and how it's displayed, making is more concise and easier to process by the human eye.

image

**Review by Tom60chat — COMMENTED** [review]
I'm not a big fan of Program.Log, Logger.Write is better.

In Settings, you have made have Discord directly but when we want to put Telegarm this meen we have to do :
```json
"Discord" : { }
"Telegram" : {]
```
not a big fan too, I would prefer doing in a another way.

**Comment by haq** [comment]
> Wait this is just a logger ?
> 
> Ok, to be fare #41 say log but I was thinking maybe make it a little more readable like a summary :
> 
> ```
> Acnt1 have made 154 point, now total is 12349
> Acnt2 have made 144 point, now total is 14326
> ...
> ```
> 
> Not to push the full log file like that.

I agree, webhook logger should only push when the farm is done.

**Review by Tom60chat — CHANGES_REQUESTED** [review]
Really nice work!

But you call your class Webhook and in the parameters you say Webhooks but I think for Telegram uses bots and not webhooks (Technically I called them like that before, I can understand the confusion), I know I'm a bit anoying about it but I want to avoid any confusion.

You can name it Output, ThirdParty, Service or sometings else if you have a better idea.

After that I will push it.

**Comment by Tom60chat** [comment]
Hum, I don't know if "Completion" and "Path" would be a good naming, But the idea sounds good to me.

**Comment by haq** [comment]
let me know what you think of the new changes

**Review by Tom60chat — APPROVED** [review]
Sounds good to me.

Big thanks for your huge effort to the project 👍

**Comment by haq** [comment]
> Sounds good to me.
> 
> Big thanks for your huge effort to the project 👍

Is there anything left to add to this pull request?

**Comment by Tom60chat** [comment]
No, just me that still didn't test it on my computer before merging it.
Maybe tomorrow.

**Pull request merged**
